# Spring configuration
# Database source configuration
spring:
  application:
    name: ChaTop-back

  datasource:
    url: jdbc:mysql://localhost:3306/chatop?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

# Server configuration
server:
  port: 3001

# Logging configuration
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN

# Springdoc configuration
springdoc:
  open-api:
    info:
      title: "ChaTop API"
      version: v1