spring:
  application:
    name: ChaTop-back

  datasource:
    url: jdbc:mysql://localhost:3306/chatop?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

server:
  port: 3001

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN