# Spring configuration
spring:
  application:
    name: ChaTop-back

  # Database source configuration
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Jackson property naming strategy configuration
  jackson:
    property-naming-strategy: SNAKE_CASE

  # Spring Cloud AWS S3 configuration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET_NAME}

  # Multipart configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server configuration
server:
  port: ${SERVER_PORT}

  # Error configuration
  error:
    include-stacktrace: never

# Logging configuration
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN