# Spring configuration
spring:
  application:
    name: ChaTop-back

  # Database source configuration
  datasource:
    url: jdbc:mysql://localhost:3306/chatop?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

  # Jackson property naming strategy configuration
  jackson:
    property-naming-strategy: SNAKE_CASE

  # Spring Cloud AWS S3 configuration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: eu-west-3
      s3:
        bucket: ${AWS_BUCKET_NAME}

  # Multipart configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server configuration
server:
  port: 3001

  # Error configuration
  error:
    include-stacktrace: never

# Logging configuration
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN

# Jwt configuration
jwt:
  key: ${JWT_KEY}